apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chronograf
  labels:
    metrics: "chronograf"
    app: cicd-chronograf
    version: "1.7.8"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi