apiVersion: v1
kind: Service
metadata:
  name: chronograf
  labels:
    metrics: "chronograf"
    app: "cicd-chronograf"
spec:
  ports:
  - name: 8888-http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    metrics: chronograf
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}